linters:
  fast: false
  disable:
    - errcheck
  enable:
    #- errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    #- cyclop
    - depguard
    - dogsled
    #- dupl
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    #- exhaustivestruct
    - exportloopref
    - forbidigo
    #- forcetypeassert
    #- funlen
    - gci
    - gochecknoglobals
    #- gocognit
    #- goconst
    #- gocritic
    #- gocyclo
    - godot
    #- godox
    #- goerr113
    - gofmt
    - gofumpt
    - goheader
    - goimports
    #- gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - importas
    #- ireturn
    - lll
    - makezero
    - misspell
    - nakedret
    #- nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - revive
    #- rowserrcheck
    #- sqlclosecheck
    - stylecheck
    #- tagliatelle
    - tenv
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    #- varnamelen
    - wastedassign
    - whitespace
    #- wrapcheck
    - wsl

run:
  tests: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  fix: true
